# XcodeGen Project Specification
# Generate Xcode project: xcodegen generate

name: ClaudeController
options:
  bundleIdPrefix: com.claudecontroller
  deploymentTarget:
    macOS: "15.0"
  xcodeVersion: "16.0"
  generateEmptyDirectories: true
  groupSortPosition: top

settings:
  base:
    PRODUCT_NAME: Claude Controller
    PRODUCT_BUNDLE_IDENTIFIER: com.claudecontroller.mac
    MARKETING_VERSION: 1.0.0
    CURRENT_PROJECT_VERSION: 1
    SWIFT_VERSION: 5.9
    MACOSX_DEPLOYMENT_TARGET: 15.0

    # Code Signing
    CODE_SIGN_STYLE: Automatic
    DEVELOPMENT_TEAM: "" # Set your team ID
    CODE_SIGN_IDENTITY: "Developer ID Application"

    # Hardened Runtime (required for notarization)
    ENABLE_HARDENED_RUNTIME: YES

    # App Sandbox DISABLED (required for CGEvent)
    ENABLE_APP_SANDBOX: NO

    # Build Settings
    SWIFT_OPTIMIZATION_LEVEL: -O
    GCC_OPTIMIZATION_LEVEL: s
    SWIFT_COMPILATION_MODE: wholemodule

    # Other
    INFOPLIST_FILE: Resources/Info.plist
    CODE_SIGN_ENTITLEMENTS: Resources/ClaudeController.entitlements
    ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    LD_RUNPATH_SEARCH_PATHS: "@executable_path/../Frameworks"
    COMBINE_HIDPI_IMAGES: YES

  configs:
    Debug:
      SWIFT_OPTIMIZATION_LEVEL: -Onone
      GCC_OPTIMIZATION_LEVEL: "0"
      SWIFT_COMPILATION_MODE: singlefile
      DEBUG_INFORMATION_FORMAT: dwarf-with-dsym
      MTL_ENABLE_DEBUG_INFO: INCLUDE_SOURCE
      ENABLE_TESTABILITY: YES
    Release:
      SWIFT_OPTIMIZATION_LEVEL: -O
      GCC_OPTIMIZATION_LEVEL: s
      DEBUG_INFORMATION_FORMAT: dwarf-with-dsym
      MTL_ENABLE_DEBUG_INFO: NO
      VALIDATE_PRODUCT: YES

targets:
  ClaudeController:
    type: application
    platform: macOS
    sources:
      - path: Sources
        excludes:
          - "**/*.md"
      - path: Resources
        type: folder
    settings:
      base:
        # Menu bar app (no dock icon by default)
        LS_UI_ELEMENT: YES

        # Minimum macOS version
        MACOSX_DEPLOYMENT_TARGET: 15.0

    dependencies: []

    preBuildScripts:
      - name: "SwiftLint"
        script: |
          if which swiftlint >/dev/null; then
            swiftlint
          else
            echo "warning: SwiftLint not installed"
          fi
        basedOnDependencyAnalysis: false

    postBuildScripts:
      - name: "Verify Entitlements"
        script: |
          echo "Verifying entitlements..."
          codesign -d --entitlements :- "${BUILT_PRODUCTS_DIR}/${PRODUCT_NAME}.app" 2>&1 | head -20
        basedOnDependencyAnalysis: false

  ClaudeControllerTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - path: Tests
    dependencies:
      - target: ClaudeController
    settings:
      base:
        BUNDLE_LOADER: "$(TEST_HOST)"
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/Claude Controller.app/Contents/MacOS/Claude Controller"

schemes:
  ClaudeController:
    build:
      targets:
        ClaudeController: all
        ClaudeControllerTests: [test]
    run:
      config: Debug
      commandLineArguments:
        "-NSConstraintBasedLayoutVisualizeMutuallyExclusiveConstraints": YES
    test:
      config: Debug
      targets:
        - ClaudeControllerTests
      gatherCoverageData: true
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
      revealArchiveInOrganizer: true

# Aggregated targets for convenience
aggregateTargets:
  BuildAll:
    targets:
      - ClaudeController
      - ClaudeControllerTests
